"""TEST-ORDER-CONTEXTVAR-1 — the sweep is only as order-independent as its ContextVars.

pytest runs every test in one ``contextvars`` context. A test that ``.set()``s a runtime
ContextVar and never resets it silently changes the ambient state of every test after it.
Measured 2026-09-13: ``test_contextvar_thread_propagation.py`` left ``pipeline_active=True``,
a trace id and a syscall ``_EU_ID_CTX`` set, so roughly 180 of 221 unit files ran with the
ExecutionContract gate vacuously satisfied — and the first symptom was a test in an unrelated
file that failed only in CI's full order (#632).

``tests/unit/conftest.py`` now snapshots every ContextVar the runtime has imported and, after
each test, resets what changed and FAILS the test that changed it. These tests guard that
fixture the only way that means anything: a **real pytest subprocess** against files generated
on the spot. A test that imported the conftest and called the fixture with a fake request would
keep passing after pytest stopped loading it (the "covers, asserts nothing" shape).

Mutation-checked: delete the ``pytest.fail`` in ``_contextvar_isolation`` and
``test_leaking_test_is_failed_and_named`` fails; delete the ``var.set(prior)`` restore and
``test_victim_after_a_leak_starts_clean`` fails; empty the census and
``test_census_is_derived_and_non_empty`` fails.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.runtime_only

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIT_DIR = Path(__file__).resolve().parent

# Leaks three vars the way the real offender did; the victim runs AFTER it in file order
# (``zz_a`` < ``zz_b``) and asserts the ambient state it inherits.
_LEAKER = '''"""Generated by test_contextvar_isolation_guard.py — safe to delete."""
from AINDY.kernel.syscall_dispatcher import _EU_ID_CTX
from AINDY.platform_layer.trace_context import set_pipeline_active, set_trace_id


def test_probe_leaks_three_contextvars():
    set_trace_id("leaked-trace")
    _EU_ID_CTX.set("leaked-eu")
    set_pipeline_active(True)
    assert True
'''

_VICTIM = '''"""Generated by test_contextvar_isolation_guard.py — safe to delete."""
from AINDY.kernel.syscall_dispatcher import _EU_ID_CTX
from AINDY.platform_layer.trace_context import get_trace_id, is_pipeline_active


def test_probe_victim_sees_clean_ambient_state():
    assert not is_pipeline_active(), "inherited pipeline_active=True from the leaker"
    assert _EU_ID_CTX.get() == "", "inherited a syscall unit id from the leaker"
    assert get_trace_id() != "leaked-trace", "inherited a trace id from the leaker"
'''


def _run(*paths: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-rEf",
         *(str(p.relative_to(REPO_ROOT)) for p in paths)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=600,
    )


@pytest.fixture
def probes():
    leaker = UNIT_DIR / "test_zz_a_probe_leaker.py"
    victim = UNIT_DIR / "test_zz_b_probe_victim.py"
    leaker.write_text(_LEAKER, encoding="utf-8")
    victim.write_text(_VICTIM, encoding="utf-8")
    try:
        yield leaker, victim
    finally:
        leaker.unlink(missing_ok=True)
        victim.unlink(missing_ok=True)


def test_leaking_test_is_failed_and_named(probes):
    """The guard must fail THE LEAKER — and say which vars — not some later test."""
    leaker, _ = probes
    result = _run(leaker)
    out = result.stdout + result.stderr

    assert result.returncode != 0, f"a test that leaked three ContextVars passed:\n{out}"
    assert "TEST-ORDER-CONTEXTVAR-1" in out, out
    assert "test_probe_leaks_three_contextvars" in out, out
    for name in ("_trace_id_ctx", "_EU_ID_CTX", "_pipeline_active_ctx"):
        assert name in out, f"the guard did not name {name}:\n{out}"


def test_victim_after_a_leak_starts_clean(probes):
    """The restore half: the leaker is failed AND the next test does not inherit its state.

    Without the reset, the guard would only move the blame; the victim would still run
    against polluted state, which is the defect this exists to remove.
    """
    leaker, victim = probes
    result = _run(leaker, victim)
    out = result.stdout + result.stderr
    reported = [ln for ln in out.splitlines() if ln.startswith(("FAILED", "ERROR"))]

    assert any("test_probe_leaks_three_contextvars" in ln for ln in reported), out
    assert not any("victim" in ln for ln in reported), (
        f"the victim inherited the leaker's state — the guard reported but did not restore:\n{out}"
    )
    assert len(reported) == 1, f"expected exactly the leaker to be reported:\n{out}"


def test_a_clean_test_is_untouched(probes):
    """Liveness for the other direction: a test that resets its own vars passes."""
    _, victim = probes
    result = _run(victim)
    assert result.returncode == 0, result.stdout + result.stderr


def test_census_is_derived_and_non_empty():
    """The census must come from the loaded runtime, and must not be empty (variant 12)."""
    import AINDY.kernel.syscall_dispatcher  # noqa: F401 - ensure at least these are loaded
    import AINDY.platform_layer.trace_context  # noqa: F401

    import importlib.util

    spec = importlib.util.spec_from_file_location("_unit_conftest", UNIT_DIR / "conftest.py")
    conftest = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(conftest)

    census = conftest._runtime_contextvars()
    labels = {label for label, _ in census}
    assert len(census) >= 5, f"census too small to be the runtime's: {sorted(labels)}"
    assert "AINDY.kernel.syscall_dispatcher._EU_ID_CTX" in labels
    assert "AINDY.platform_layer.trace_context._pipeline_active_ctx" in labels
