"""CI-MARKER-1 — a unit test that is not selected by CI is not coverage.

`Runtime Contracts` is the only job that runs unit tests, and it runs
``pytest tests -m runtime_only``. Nothing applied that marker automatically, so
for the life of the repo a new file under ``tests/unit/`` defaulted to running
in **no** job while its pull request stayed green. 268 tests across 24 files sat
in that state, including the regressions for the three defects that forced the
2.0.1 release — meaning those fixes could have been reverted with CI green.

``tests/unit/conftest.py`` now defaults every unit item into the marker. These
tests guard that hook, and they guard it the only way that means anything:
by running a **real pytest subprocess** against files generated on the spot.
A test that merely imported the conftest and called the hook with a fake item
would keep passing after pytest stopped loading the hook at all — the same
"covers, asserts nothing" shape this repo has now hit six times.

Mutation-checked: delete the ``item.add_marker`` line in ``tests/unit/conftest.py``
and ``test_unmarked_unit_file_is_collected`` fails; drop the
``FOREIGN_JOB_MARKERS`` branch and ``test_foreign_job_marker_opts_out`` fails;
unmark any one file with the hook gone and
``test_no_unit_test_escapes_the_marker`` fails.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.runtime_only

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIT_DIR = Path(__file__).resolve().parent

_UNMARKED_PROBE = '''"""Generated by test_ci_marker_default.py — safe to delete."""


def test_probe_unmarked():
    assert True
'''

_OPTED_OUT_PROBE = '''"""Generated by test_ci_marker_default.py — safe to delete."""
import pytest

pytestmark = pytest.mark.integration


def test_probe_opted_out():
    assert True
'''


def _collect(*args: str) -> list[str]:
    """Collect-only in a subprocess; return the ``tests/...`` lines it reports.

    ``--collect-only -q`` reports one ``<path>: <count>`` line per file that
    contributed at least one selected test, so a file absent from this list
    contributed nothing.
    """
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider", *args],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=600,
    )
    # 0 = collected something, 5 = EXIT_NOTESTSCOLLECTED. Both are valid answers
    # here; anything else means collection itself broke and the result is not a
    # measurement of what is selected.
    assert result.returncode in (0, 5), (
        f"collection failed (rc={result.returncode}):\n{result.stdout}\n{result.stderr}"
    )
    return [
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip().startswith("tests/") and ".py" in line
    ]


@pytest.fixture
def probes():
    """Write two probe files into tests/unit and remove them afterwards."""
    unmarked = UNIT_DIR / "test_zz_probe_unmarked.py"
    opted_out = UNIT_DIR / "test_zz_probe_opted_out.py"
    unmarked.write_text(_UNMARKED_PROBE, encoding="utf-8")
    opted_out.write_text(_OPTED_OUT_PROBE, encoding="utf-8")
    try:
        yield unmarked, opted_out
    finally:
        unmarked.unlink(missing_ok=True)
        opted_out.unlink(missing_ok=True)


def test_unmarked_unit_file_is_collected(probes):
    """A brand-new unit file with no marker must still run in `Runtime Contracts`.

    This is the whole point of CI-MARKER-1: the default has to be safe, because
    the failure mode of the old default was invisible.
    """
    unmarked, opted_out = probes
    collected = _collect(str(unmarked.relative_to(REPO_ROOT)),
                         str(opted_out.relative_to(REPO_ROOT)),
                         "-m", "runtime_only")

    assert any(unmarked.name in line for line in collected), (
        "An unmarked tests/unit file was NOT collected by `-m runtime_only`. "
        "The auto-marker hook in tests/unit/conftest.py is not running, so new "
        f"unit tests silently run in no CI job.\nCollected: {collected}"
    )


def test_foreign_job_marker_opts_out(probes):
    """A unit test claimed by another job must stay out of the runtime job."""
    unmarked, opted_out = probes
    collected = _collect(str(unmarked.relative_to(REPO_ROOT)),
                         str(opted_out.relative_to(REPO_ROOT)),
                         "-m", "runtime_only")

    assert not any(opted_out.name in line for line in collected), (
        "A test marked `integration` was pulled into the runtime_only job. "
        "The FOREIGN_JOB_MARKERS opt-out in tests/unit/conftest.py is not "
        f"working.\nCollected: {collected}"
    )


def test_no_unit_test_escapes_the_marker():
    """Nothing under tests/unit may fall outside `-m runtime_only`.

    Selecting the complement should collect zero tests. If this fails, read the
    node ids it prints: either the auto-marker regressed, or someone added a
    deliberate opt-out — in which case add its marker to FOREIGN_JOB_MARKERS
    and to the allowance below, rather than deleting this assertion.
    """
    escaped = _collect("tests/unit", "-m", "not runtime_only")

    assert not escaped, (
        "These tests/unit files contain tests that `Runtime Contracts` does not "
        "select, and therefore run in no CI job:\n  " + "\n  ".join(escaped)
    )
