"""TEST-ORDER-RUNTIME-STATE-1 — the published deployment profile must not leak between tests.

`deployment_contract._api_runtime_state` is a process-global dict that three runtime readers
consult BEFORE `AINDY_DEPLOYMENT_PROFILE`. A test that published a profile and kept it shadowed
the env var for every test after it; a test that reset it to `unknown` UN-shadowed it. One test
(`test_container_runner_unavailable_fails_closed_without_fallback`) passed only while shadowed.

`tests/unit/conftest.py::_published_runtime_state_isolation` restores both published dicts after
every test, silently (DEC-082: this state is always fully restorable, so the restore alone removes
the order dependence). Guarded the only way that means anything: a real pytest subprocess against
files generated on the spot (the shape of `test_contextvar_isolation_guard.py`).

Mutation-checked: delete the restore → the victim fails in both tests below.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.runtime_only

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIT_DIR = Path(__file__).resolve().parent

_LEAKER = '''"""Generated by test_published_state_isolation_guard.py — safe to delete."""
from AINDY.platform_layer.deployment_contract import publish_api_runtime_state


def test_probe_publishes_a_profile_and_keeps_it():
    from AINDY.platform_layer.deployment_contract import get_api_runtime_state

    publish_api_runtime_state(deployment_profile="distributed-api", deployment_profile_source="probe")
    assert get_api_runtime_state()["deployment_profile"] == "distributed-api"
'''

_BOOKKEEPER = '''"""Generated by test_published_state_isolation_guard.py — safe to delete."""
from AINDY.platform_layer.deployment_contract import publish_api_runtime_state


def test_probe_changes_only_bookkeeping():
    publish_api_runtime_state(runtime_conditions={"probe": True}, startup_complete=True)
'''

_VICTIM = '''"""Generated by test_published_state_isolation_guard.py — safe to delete."""
from AINDY.platform_layer.deployment_contract import get_api_runtime_state


def test_probe_victim_reads_clean_state():
    state = get_api_runtime_state()
    assert state["deployment_profile"] != "distributed-api", "inherited the leaker's profile"
    assert state["deployment_profile_source"] != "probe", "inherited the leaker's source"
    assert "probe" not in (state.get("runtime_conditions") or {}), "inherited the bookkeeper's conditions"
'''

_CLEAN = '''"""Generated by test_published_state_isolation_guard.py — safe to delete."""
from AINDY.platform_layer import deployment_contract as dc


def test_probe_publishes_through_monkeypatch(monkeypatch):
    monkeypatch.setitem(dc._api_runtime_state, "deployment_profile", "distributed-api")
    assert dc.get_api_runtime_state()["deployment_profile"] == "distributed-api"
'''


def _run(*paths: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-rA",
         *(str(p.relative_to(REPO_ROOT)) for p in paths)],
        cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=600,
    )


@pytest.fixture
def probes():
    files = {
        "leaker": UNIT_DIR / "test_zz_rs_a_probe_leaker.py",
        "bookkeeper": UNIT_DIR / "test_zz_rs_b_probe_bookkeeper.py",
        "victim": UNIT_DIR / "test_zz_rs_c_probe_victim.py",
        "clean": UNIT_DIR / "test_zz_rs_d_probe_clean.py",
    }
    for key, body in (("leaker", _LEAKER), ("bookkeeper", _BOOKKEEPER), ("victim", _VICTIM), ("clean", _CLEAN)):
        files[key].write_text(body, encoding="utf-8")
    try:
        yield files
    finally:
        for path in files.values():
            path.unlink(missing_ok=True)


def _reported(result):
    out = result.stdout + result.stderr
    return out, [ln for ln in out.splitlines() if ln.startswith(("FAILED", "ERROR"))]


def test_the_victim_after_a_leak_reads_the_state_it_started_with(probes):
    """The leaker's publish took effect (it asserts so), and the next test does not see it."""
    result = _run(probes["leaker"], probes["bookkeeper"], probes["victim"])
    out, reported = _reported(result)
    assert result.returncode == 0 and reported == [], f"the victim inherited published state:\n{out}"
    assert sum(ln.startswith("PASSED") for ln in out.splitlines()) == 3, out


def test_a_test_publishing_through_monkeypatch_is_clean(probes):
    result = _run(probes["clean"], probes["victim"])
    out, reported = _reported(result)
    assert result.returncode == 0 and reported == [], out
    assert sum(ln.startswith("PASSED") for ln in out.splitlines()) == 2, out
